spring.application.name=Cloud-Gateway
logging.level.com.Gateway.Manas=debug
server.port=7009
spring.config.import=optional:configserver:

spring.cloud.config.uri=http://localhost:9196

spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.routes[0].id=UCSP
spring.cloud.gateway.routes[0].uri=lb://UCSP
spring.cloud.gateway.routes[0].predicates[0]=Path=/VehicleService/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[1].id=IDENTITY-SERVICE
spring.cloud.gateway.routes[1].uri=lb://IDENTITY-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[2].id=CartService
spring.cloud.gateway.routes[2].uri=lb://CartService
spring.cloud.gateway.routes[2].predicates[0]=Path=/CartAPI/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[3].id=CouponService
spring.cloud.gateway.routes[3].uri=lb://CouponService
spring.cloud.gateway.routes[3].predicates[0]=Path=/CouponAPI/**
spring.cloud.gateway.routes[3].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[4].id=checkoutService
spring.cloud.gateway.routes[4].uri=lb://checkoutService
spring.cloud.gateway.routes[4].predicates[0]=Path=/CheckoutAPI/**
spring.cloud.gateway.routes[4].filters[0]=AuthenticationFilter