spring.application.name=checkoutService


server.port = 1113
spring.config.import=optional:configserver:


spring.datasource.url=jdbc:mysql://localhost:3306/checkout_service
spring.datasource.username=root
spring.datasource.password=Manas098#
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
springdoc.api-docs.path=/checkout-docs

spring.cloud.config.uri=http://localhost:9196