spring.application.name=Service-Registery
server.port=8761

# Enable health endpoint for monitoring
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Service Registry does not register itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Allow other services to register with Eureka using Docker service name
eureka.instance.hostname=service-registry
