spring.application.name=UCSP
spring.config.import=optional:configserver:

server.port = 1111


spring.datasource.url=jdbc:mysql://localhost:3306/ucsp
spring.datasource.username=root
spring.datasource.password=Manas098#
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
springdoc.api-docs.path=/vehicle-docs

spring.cloud.config.uri=http://localhost:9196