spring.application.name=UCSP
server.port=1111

# Connect to Config Server using Docker service name
spring.config.import=optional:configserver:
spring.cloud.config.uri=http://config-server:9196

# Enable health endpoint for monitoring
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Database configuration (Connect to local MySQL using host.docker.internal)
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/ucsp
spring.datasource.username=root
spring.datasource.password=Manas098#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=vehicle-service
eureka.instance.ip-address=vehicle-service

# Swagger API docs
springdoc.api-docs.path=/vehicle-docs
